interface Banners {
    banners: BannerInfo[],
    code: number
}
interface BannerInfo {
    adDispatchJson: null,
    adLocation: null,
    adSource: null,
    adid: null,
    bannerBizType: string,
    encodeId: string,
    event: null,
    exclusive: boolean,
    extMonitor: null,
    extMonitorInfo: null,
    imageUrl: string,
    monitorBlackList: null,
    monitorClick: null,
    monitorClickList: null,
    monitorImpress: null,
    monitorImpressList: null,
    monitorType: null,
    program: null,
    scm: string,
    song: null,
    targetId: number,
    targetType: number,
    titleColor: string,
    typeTitle: string,
    url: string,
    video: null,
}